### PR TITLE
Fix #33: The tiniest patch you can get to acquire perl 5.26 compatibility.

### LINKED ISSUE #33: Padre does not work with Perl 5.26 (unicode error)
After installing the required packages from debian testing and installing Padre, the following error occurs:

```
Malformed UTF-8 character: \xe0\x20\x6c (unexpected non-continuation byte 0x20, immediately after start byte 0xe0; need 3 bytes, got 1) at /usr/local/share/perl/5.26.1/Padre/Wx/Main.pm line 5564.
Malformed UTF-8 character (fatal) at /usr/local/share/perl/5.26.1/Padre/Wx/Main.pm line 5564.
Compilation failed in require at /usr/local/share/perl/5.26.1/Padre/Wx/App.pm line 58.
Perl exited with active threads:
        1 running and unjoined
        0 finished and unjoined
        0 running and detached
```
If the mentioned character (`à`)  is eliminated and a reinstall is performed, Padre works fine.

### PR DESCRIPTION
**Pull request by lapawa**
It just replaces a malformed UTF8 character.
#33

### CODE REVIEW

**Comment by szabgab** [comment]
Unfortunately the Travis-CI tests are failing, but it seems unrelated to this change so I've merged it.

Thank you!
