### ISSUE TITLE
Padre does not work with Perl 5.26 (unicode error)

### ISSUE THREAD

**Issue by meetunix** [PadreIDE/Padre#33]
After installing the required packages from debian testing and installing Padre, the following error occurs:

```
Malformed UTF-8 character: \xe0\x20\x6c (unexpected non-continuation byte 0x20, immediately after start byte 0xe0; need 3 bytes, got 1) at /usr/local/share/perl/5.26.1/Padre/Wx/Main.pm line 5564.
Malformed UTF-8 character (fatal) at /usr/local/share/perl/5.26.1/Padre/Wx/Main.pm line 5564.
Compilation failed in require at /usr/local/share/perl/5.26.1/Padre/Wx/App.pm line 58.
Perl exited with active threads:
        1 running and unjoined
        0 finished and unjoined
        0 running and detached
```
If the mentioned character (`à`)  is eliminated and a reinstall is performed, Padre works fine.

**Comment by szabgab** [comment]
Thanks for reporting though I don't know if anyone will have the time to fix this.

**Comment by lapawa** [comment]
This failure is generated by a single character. Just remove it and everything is fine.

**Comment by davebaird** [comment]
For anyone who wants to get Padre running on recent Strawberry Perl, it's pretty straightforward - see https://paulshipley.id.au/blog/coding-tips/ide-for-strawberry-perl-for-windows/ 

As of writing, Perl 5.30 has a different issue (Wx is broken) which prevents Padre installation, so stick to 5.28 until that's dealt with.
